name: Daily Code Execution

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: '0 0 * * *'
  push:
    # Optionally specify branches if needed
    branches:
      - master  # Change 'master' to the default branch of your repository if it's different

jobs:
  execute-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create data directory
        run: |
          mkdir -p data  # Create the data directory if it doesn't exist

      - name: Create JSON for Token
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "data/token.json"  # Specify the path where the JSON file will be created
          json: ${{ secrets.TOKEN_CONFIG_JSON }}  # Use the secret for the JSON content

      - name: Install dependencies for Google API
        run: |
          pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Execute script
        run: |
          cat data/token.json
          chmod +x script.sh # Make the script executable
          ./script.sh # Run the script

      - name: Configure Git
        run: |
          echo ${{ secrets.USERNAME }}
          echo ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}

      - name: Add changes to git
        run: |
          git add README.md ./data

      - name: Commit changes
        run: |
          git commit -m "Daily Code Execution GitHub Action" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin master
